Moved pretend update after portage and profile update.

diff --git a/bin/update-system b/bin/update-system
--- a/bin/update-system
+++ b/bin/update-system
@@ -140,65 +140,57 @@ fi
 
 echo -e "Starting automated update of $(hostname --long)\n"
 
-# Do a pretend update for the logs
-echo -n "Performing pretend update..."
-exec_and_log pretend_update "emerge --color n --nospinner --pretend --verbose ${UPDATE_OPTS}"
-okorfail 4
+# Store and display current key package versions and slots.
+PRE_PERL_PKG=$(qlist -I -C -v -e dev-lang/perl)
+PRE_PYTHON_PKGS=$(qlist -I -C -v -e dev-lang/python | xargs)
+PRE_PYTHON_SLOT=$(qlist -I -C -S -e dev-lang/python | cut -f 2 -d " " | cut -f 2 -d ":" | xargs)
+PRE_PORTAGE_PKG=$(qlist -I -C -v -e sys-apps/portage)
+PRE_GCC_PKGS=$(qlist -I -C -v -e sys-devel/gcc | xargs)
+PRE_GCC_SLOT=$(qlist -I -C -S -e sys-devel/gcc | cut -f 2 -d " " | cut -f 2 -d ":" | xargs)
+PRE_HEADERS_PKG=$(qlist -I -C -v -e sys-kernel/linux-headers)
+PRE_GLIBC_PKG=$(qlist -I -C -v -e sys-libs/glibc)
+PRE_XORG_PKG=$(qlist -I -C -v -e x11-base/xorg-server)
+PRE_XDRV_PKG=$(qlist -I -C -v -e x11-base/xorg-drivers)
 
-# If things are still working so far...
-if (( ! ${EXITSTATUS} )); then
-	# Store and display current key package versions and slots.
-	PRE_PERL_PKG=$(qlist -I -C -v -e dev-lang/perl)
-	PRE_PYTHON_PKGS=$(qlist -I -C -v -e dev-lang/python | xargs)
-	PRE_PYTHON_SLOT=$(qlist -I -C -S -e dev-lang/python | cut -f 2 -d " " | cut -f 2 -d ":" | xargs)
-	PRE_PORTAGE_PKG=$(qlist -I -C -v -e sys-apps/portage)
-	PRE_GCC_PKGS=$(qlist -I -C -v -e sys-devel/gcc | xargs)
-	PRE_GCC_SLOT=$(qlist -I -C -S -e sys-devel/gcc | cut -f 2 -d " " | cut -f 2 -d ":" | xargs)
-	PRE_HEADERS_PKG=$(qlist -I -C -v -e sys-kernel/linux-headers)
-	PRE_GLIBC_PKG=$(qlist -I -C -v -e sys-libs/glibc)
-	PRE_XORG_PKG=$(qlist -I -C -v -e x11-base/xorg-server)
-	PRE_XDRV_PKG=$(qlist -I -C -v -e x11-base/xorg-drivers)
+[[ -z "${PRE_PERL_PKG}" ]] && echo "Error: Unable to retrieve current dev-lang/perl version" && exit 4
+[[ -z "${PRE_PYTHON_PKGS}" || -z "${PRE_PYTHON_SLOT}" ]] && echo "Error: Unable to retrieve current dev-lang/python version" && exit 4
+[[ -z "${PRE_PORTAGE_PKG}" ]] && echo "Error: Unable to retrieve current sys-apps/portage version" && exit 4
+[[ -z "${PRE_GCC_PKGS}" || -z "${PRE_GCC_SLOT}" ]] && echo "Error: Unable to retrieve current sys-devel/gcc version" && exit 4
+[[ -z "${PRE_HEADERS_PKG}" ]] && echo "Error: Unable to retrieve current sys-kernel/linux-headers version" && exit 4
+[[ -z "${PRE_GLIBC_PKG}" ]] && echo "Error: Unable to retrieve current sys-libs/glibc version" && exit 4
 	
-	[[ -z "${PRE_PERL_PKG}" ]] && echo "Error: Unable to retrieve current dev-lang/perl version" && exit 4
-	[[ -z "${PRE_PYTHON_PKGS}" || -z "${PRE_PYTHON_SLOT}" ]] && echo "Error: Unable to retrieve current dev-lang/python version" && exit 4
-	[[ -z "${PRE_PORTAGE_PKG}" ]] && echo "Error: Unable to retrieve current sys-apps/portage version" && exit 4
-	[[ -z "${PRE_GCC_PKGS}" || -z "${PRE_GCC_SLOT}" ]] && echo "Error: Unable to retrieve current sys-devel/gcc version" && exit 4
-	[[ -z "${PRE_HEADERS_PKG}" ]] && echo "Error: Unable to retrieve current sys-kernel/linux-headers version" && exit 4
-	[[ -z "${PRE_GLIBC_PKG}" ]] && echo "Error: Unable to retrieve current sys-libs/glibc version" && exit 4
-		
-	echo -e "\nKey package versions [pre update]"
-	echo "    ${PRE_PERL_PKG}"
-	echo "    ${PRE_PYTHON_PKGS} in slot(s) ${PRE_PYTHON_SLOT}"
-	echo "    ${PRE_PORTAGE_PKG}"
-	echo "    ${PRE_GCC_PKGS} in slot(s) ${PRE_GCC_SLOT}"
-	echo "    ${PRE_HEADERS_PKG}"
-	echo "    ${PRE_GLIBC_PKG}"
-	[[ -n "${PRE_XORG_PKG}" ]] && echo "    ${PRE_XORG_PKG}"
-	[[ -n "${PRE_XDRV_PKG}" ]] && echo "    ${PRE_XDRV_PKG}"
+echo -e "\nKey package versions [pre update]"
+echo "    ${PRE_PERL_PKG}"
+echo "    ${PRE_PYTHON_PKGS} in slot(s) ${PRE_PYTHON_SLOT}"
+echo "    ${PRE_PORTAGE_PKG}"
+echo "    ${PRE_GCC_PKGS} in slot(s) ${PRE_GCC_SLOT}"
+echo "    ${PRE_HEADERS_PKG}"
+echo "    ${PRE_GLIBC_PKG}"
+[[ -n "${PRE_XORG_PKG}" ]] && echo "    ${PRE_XORG_PKG}"
+[[ -n "${PRE_XDRV_PKG}" ]] && echo "    ${PRE_XDRV_PKG}"
+echo
+											
+# Ensure that key slotted packages are specified in world file and include slot number
+if [[ -n $(manage-slot-in-world --add-installed --pretend ${KEEP_PACKAGES}) ]]; then
+	echo "Ensuring that key packages are in world file and include slot number"
+	manage-slot-in-world --add-installed ${KEEP_PACKAGES}
 	echo
-												
-	# Ensure that key slotted packages are specified in world file and include slot number
-	if [[ -n $(manage-slot-in-world --add-installed --pretend ${KEEP_PACKAGES}) ]]; then
-		echo "Ensuring that key packages are in world file and include slot number"
-		manage-slot-in-world --add-installed ${KEEP_PACKAGES}
-		echo
-	fi 
+fi 
 
-	# Check for an update to portage (and its dependencies if there is one) and install them.
-	if update_available "sys-apps/portage";	then
-		portage_deps=""
-		for pkg in ${PORTAGE_DEPS}; do
-			if update_available "${pkg}"; then
-				portage_deps="${portage_deps} ${pkg}"
-			fi
-		done
-		portage_deps="${portage_deps} sys-apps/portage"
-		portage_deps="${portage_deps## }"
-		
-		echo -n "Performing update of portage and dependencies [${portage_deps}]..."
-		exec_and_log portage_update "emerge --color n --nospinner --oneshot --update --complete-graph=y --with-bdeps=y ${portage_deps}"
-		okorfail 6
-	fi
+# Check for an update to portage (and its dependencies if there is one) and install them.
+if update_available "sys-apps/portage";	then
+	portage_deps=""
+	for pkg in ${PORTAGE_DEPS}; do
+		if update_available "${pkg}"; then
+			portage_deps="${portage_deps} ${pkg}"
+		fi
+	done
+	portage_deps="${portage_deps} sys-apps/portage"
+	portage_deps="${portage_deps## }"
+	
+	echo -n "Performing update of portage and dependencies [${portage_deps}]..."
+	exec_and_log portage_update "emerge --color n --nospinner --oneshot --update --complete-graph=y --with-bdeps=y ${portage_deps}"
+	okorfail 6
 fi
 
 # If things are still working so far...
@@ -214,6 +206,14 @@ if (( ! ${EXITSTATUS} )); then
 		env-update &>/dev/null
 		source /etc/profile &>/dev/null
 	fi
+fi
+
+# If things are still working so far...
+if (( ! ${EXITSTATUS} )); then
+	# Do a pretend update for the logs
+	echo -n "Performing pretend update..."
+	exec_and_log pretend_update "emerge --color n --nospinner --pretend --verbose ${UPDATE_OPTS}"
+	okorfail 4
 fi
 
 # If things are still working so far...
